### ISSUE TITLE
 rq03.2 is still failing

### ISSUE THREAD

**Issue by kouess6** [jhu-ep-coursera/fullstack-course2-module1-fancy_cars#1]
I try many methods to create todolist.
The assignment.create_todolist(:name=> 'mylist', :due_date=>due_date) returns errors.

I read the tip you gave on FAQ but i think i have not really unsterdood it.
(apologizes for my bad english, i'm a french man)

**Comment by kalmanh** [comment]
TodoList does not have attribute "name" and "due_date". They are called "list_name" and "list_due_date"

Hopefully that makes it more clear.
